.TH "E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/INC/bc12f683-config-29.h" 3 "Tue Dec 10 2013" "I2C LCD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/INC/bc12f683-config-29.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBoption_reg\fP = 0xb11111111"
.br
.ti -1c
.RI "\fBintcon\fP = 0b00000000"
.br
.ti -1c
.RI "\fBpie1\fP = 0x00000000"
.br
.ti -1c
.RI "\fBpir1\fP = 0b00000000"
.br
.ti -1c
.RI "\fBpcon\fP = 0b00000000"
.br
.ti -1c
.RI "\fBosctune\fP = 0b00000000"
.br
.ti -1c
.RI "\fBosccon\fP = 0b01110000"
.br
.ti -1c
.RI "\fBgpio\fP = 0b00000000"
.br
.ti -1c
.RI "\fBtrisio\fP = 0b00111000"
.br
.ti -1c
.RI "\fBwpu\fP = 0b00000000"
.br
.ti -1c
.RI "\fBioc\fP = 0b00000000"
.br
.ti -1c
.RI "\fBt1con\fP = 0b00000100"
.br
.ti -1c
.RI "\fBt2con\fP = 0b00000000"
.br
.ti -1c
.RI "\fBcmcon0\fP = 0b00000111"
.br
.ti -1c
.RI "\fBcmcon1\fP = 0b00000000"
.br
.ti -1c
.RI "\fBvrcon\fP = 0b00000000"
.br
.ti -1c
.RI "\fBadcon0\fP = 0b10001100"
.br
.ti -1c
.RI "\fBansel\fP = 0b00000000"
.br
.ti -1c
.RI "\fBccp1con\fP = 0b00000000"
.br
.ti -1c
.RI "\fBwdtcon\fP = 0b00001000"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "adcon0 = 0b10001100"

.SS "ansel = 0b00000000"

.SS "ccp1con = 0b00000000"

.SS "cmcon0 = 0b00000111"

.SS "cmcon1 = 0b00000000"

.SS "gpio = 0b00000000"

.SS "intcon = 0b00000000"

.SS "ioc = 0b00000000"

.SS "option_reg = 0xb11111111"

.SS "osccon = 0b01110000"

.SS "osctune = 0b00000000"

.SS "pcon = 0b00000000"

.SS "pie1 = 0x00000000"

.SS "pir1 = 0b00000000"

.SS "t1con = 0b00000100"

.SS "t2con = 0b00000000"

.SS "trisio = 0b00111000"

.SS "vrcon = 0b00000000"

.SS "wdtcon = 0b00001000"

.SS "wpu = 0b00000000"

.SH "Author"
.PP 
Generated automatically by Doxygen for I2C LCD from the source code\&.
