.TH "E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/INC/CPIC12F683.h" 3 "Tue Dec 10 2013" "I2C LCD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/INC/CPIC12F683.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_PIC12F683\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "_IESO_OFF &_BOD_OFF &_CPD_OFF 
.br
&_CP_OFF &_MCLRE_OFF 
.br
&_PWRTE_OFF &_WDT_OFF & \fB_INTOSCIO\fP"
.br
.RI "\fI< Clock frequency in Hz \fP"
.ti -1c
.RI "rom char * \fBpicid\fP = '12F638-002-009'"
.br
.RI "\fIEmbeded ID string\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _PIC12F683"

.SH "Variable Documentation"
.PP 
.SS "_IESO_OFF& _BOD_OFF& _CPD_OFF& _CP_OFF& _MCLRE_OFF& _PWRTE_OFF& _WDT_OFF& _INTOSCIO"

.PP
< Clock frequency in Hz 
.SS "rom char* picid = '12F638-002-009'"

.PP
Embeded ID string\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for I2C LCD from the source code\&.
