.TH "E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/INC/I2CLCD-mkjdz.h" 3 "Tue Dec 10 2013" "I2C LCD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/INC/I2CLCD-mkjdz.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <system\&.h>\fP
.br
\fC#include 'i2c\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDIN\fP   1"
.br
.ti -1c
.RI "#define \fBDOUT\fP   0"
.br
.ti -1c
.RI "#define \fBI2C_LCD_ADDR\fP   0b01000000"
.br
.ti -1c
.RI "#define \fBI2C_LCD_BL\fP   7"
.br
.ti -1c
.RI "#define \fBI2C_LCD_RS\fP   6"
.br
.ti -1c
.RI "#define \fBI2C_LCD_RW\fP   5"
.br
.ti -1c
.RI "#define \fBI2C_LCD_EN\fP   4"
.br
.ti -1c
.RI "#define \fBI2C_LCD_D7\fP   3"
.br
.ti -1c
.RI "#define \fBI2C_LCD_D6\fP   2"
.br
.ti -1c
.RI "#define \fBI2C_LCD_D5\fP   1"
.br
.ti -1c
.RI "#define \fBI2C_LCD_D4\fP   0"
.br
.ti -1c
.RI "#define \fBCMD\fP   0x10"
.br
.ti -1c
.RI "#define \fBDATA\fP   0x50"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CMD   0x10"

.SS "#define DATA   0x50"

.SS "#define DIN   1"

.SS "#define DOUT   0"

.SS "#define I2C_LCD_ADDR   0b01000000"

.SS "#define I2C_LCD_BL   7"

.SS "#define I2C_LCD_D4   0"

.SS "#define I2C_LCD_D5   1"

.SS "#define I2C_LCD_D6   2"

.SS "#define I2C_LCD_D7   3"

.SS "#define I2C_LCD_EN   4"

.SS "#define I2C_LCD_RS   6"

.SS "#define I2C_LCD_RW   5"

.SH "Author"
.PP 
Generated automatically by Doxygen for I2C LCD from the source code\&.
