.TH "E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/SRC/itoa.c" 3 "Tue Dec 10 2013" "I2C LCD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/SRC/itoa.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <system\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBitoa\fP (int val, int base)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void itoa (intval, intbase)"

.SH "Author"
.PP 
Generated automatically by Doxygen for I2C LCD from the source code\&.
