.TH "E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/SRC/ltostr.c" 3 "Tue Dec 10 2013" "I2C LCD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/SRC/ltostr.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'INC\\ltostr\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBltostr\fP (long num, char max_chars, char dp, char *string)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ltostr (longnum, charmax_chars, chardp, char *string)"

.SH "Author"
.PP 
Generated automatically by Doxygen for I2C LCD from the source code\&.
