.TH "E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/INC/ltostr.h" 3 "Tue Dec 10 2013" "I2C LCD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/INC/ltostr.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <system\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIZE\fP   9"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBltostr\fP (long num, char max_chars, char dp, char *string)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SIZE   9"

.SH "Function Documentation"
.PP 
.SS "void ltostr (longnum, charmax_chars, chardp, char *string)"

.SH "Author"
.PP 
Generated automatically by Doxygen for I2C LCD from the source code\&.
