.TH "E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/INC/swi2c.h" 3 "Tue Dec 10 2013" "I2C LCD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/INC/swi2c.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <system\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDELAY_1\fP   2"
.br
.ti -1c
.RI "#define \fBi2c_high_sda\fP()"
.br
.ti -1c
.RI "#define \fBi2c_low_sda\fP()"
.br
.ti -1c
.RI "#define \fBi2c_high_scl\fP()"
.br
.ti -1c
.RI "#define \fBi2c_low_scl\fP()"
.br
.ti -1c
.RI "#define \fBi2c_nack\fP()"
.br
.ti -1c
.RI "#define \fBi2c_ack\fP()"
.br
.ti -1c
.RI "#define \fBi2c_start\fP()"
.br
.ti -1c
.RI "#define \fBi2c_stop\fP()"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBi2c_init\fP (void)"
.br
.ti -1c
.RI "char \fBi2c_in_byte\fP (void)"
.br
.ti -1c
.RI "void \fBi2c_out_byte\fP (char o_byte)"
.br
.ti -1c
.RI "void \fBi2c_write_byte\fP (char dev_addr, char idata)"
.br
.ti -1c
.RI "char \fBi2c_read_byte\fP (char dev_addr)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DELAY_1   2"

.SS "#define i2c_ack()"
\fBValue:\fP
.PP
.nf
i2c_low_sda(); \\
						i2c_high_scl(); \\
						i2c_low_scl(); \\
						i2c_high_sda()
.fi
.SS "#define i2c_high_scl()"
\fBValue:\fP
.PP
.nf
i2c_tris\&.SCL = 1; \
                        while(!i2c_port\&.SCL); \
                        delay_us(DELAY_1)
.fi
.SS "#define i2c_high_sda()"
\fBValue:\fP
.PP
.nf
i2c_tris\&.SDA = 1; \
                        delay_us(DELAY_1)
.fi
.SS "#define i2c_low_scl()"
\fBValue:\fP
.PP
.nf
i2c_tris\&.SCL = 0; \
                        i2c_port\&.SCL = 0; \
                        delay_us(DELAY_1)
.fi
.SS "#define i2c_low_sda()"
\fBValue:\fP
.PP
.nf
i2c_tris\&.SDA = 0; \
                        i2c_port\&.SDA = 0; \
                        delay_us(DELAY_1)
.fi
.SS "#define i2c_nack()"
\fBValue:\fP
.PP
.nf
i2c_high_sda(); \\
						i2c_high_scl(); \\
						i2c_low_scl()
.fi
.SS "#define i2c_start()"
\fBValue:\fP
.PP
.nf
i2c_low_scl(); \\
						i2c_high_scl(); \\
						i2c_low_sda(); \\
						i2c_low_scl()
.fi
.SS "#define i2c_stop()"
\fBValue:\fP
.PP
.nf
i2c_low_scl(); \\
						i2c_low_sda(); \\
						i2c_high_scl(); \\
						i2c_high_sda()
.fi
.SH "Function Documentation"
.PP 
.SS "char i2c_in_byte (void)"
\&.\&.\&. text \&.\&.\&. 
.SS "void i2c_init (void)"
\&.\&.\&. text \&.\&.\&. 
.SS "void i2c_out_byte (charo_byte)"

.SS "char i2c_read_byte (chardev_addr)"

.SS "void i2c_write_byte (chardev_addr, charidata)"

.SH "Author"
.PP 
Generated automatically by Doxygen for I2C LCD from the source code\&.
