.TH "E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/SRC/swi2c.c" 3 "Tue Dec 10 2013" "I2C LCD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/29-I2C_LCD/SOFTWARE/BOOSTC/PIC12F683/SRC/swi2c.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'INC\\swi2c\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBi2c_init\fP (void)"
.br
.ti -1c
.RI "char \fBi2c_in_byte\fP (void)"
.br
.ti -1c
.RI "void \fBi2c_out_byte\fP (char o_byte)"
.br
.ti -1c
.RI "void \fBi2c_write_byte\fP (char dev_addr, char idata)"
.br
.ti -1c
.RI "char \fBi2c_read_byte\fP (char dev_addr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char i2c_in_byte (void)"
\&.\&.\&. text \&.\&.\&. 
.SS "void i2c_init (void)"
\&.\&.\&. text \&.\&.\&. 
.SS "void i2c_out_byte (charo_byte)"

.SS "char i2c_read_byte (chardev_addr)"

.SS "void i2c_write_byte (chardev_addr, charidata)"

.SH "Author"
.PP 
Generated automatically by Doxygen for I2C LCD from the source code\&.
